pipeline {
    agent any


    stages {

        stage("Build") {
            steps { 
		    app = docker.build("miapache")
	    }
	}
	    stage("Lanzar"){
		    steps {
		    sh 'docker run -d --name apache -p 81:80 miapache'
		} // del step
	} //del stage
    } // del stages
} // del pipeline

